# Generated by Django 3.0.5 on 2020-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
